document.write(`<div class = "footer-container">`);
document.write(`<div class = "footer-side" >`);
document.write(`<p class = "footer-title">Hours</p>`);
document.write(`<div class  = "hours">`);
document.write(`<p class = "footer-hours">Monday - Friday: 10:00 a.m. - 5:00 p.m.<br>Saturday: 9:00 a.m. - 6:00 p.m.<br>Sunday: 11:00 a.m. - 4:00 p.m.</p>`);
document.write(`</div>`);
document.write(`</div>`);
document.write(`<div class = "footer-middle">`);
document.write(`<p class = "footer-title pacifica">Pacifica</p>`);
document.write(`<p class = "footer-text">We at Pacifica are commited to giving each customer a satisfying, relaxing, and enjoyable experience.</p>`);
document.write(`<ul class="social-icons">`);
document.write(`<li><a class="facebook" target = "_blank" href="https://facebook.com/"><i class="fa fa-facebook"></i></a></li>`);
document.write(`<li><a class="twitter" target = "_blank" href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>`);
document.write(`<li><a class="linkedin" target = "_blank" href="https://instagram.com/"><i class="fa fa-instagram"></i></a></li>`);
document.write(`</ul>`);
document.write(`</div>`);
document.write(`<div class = "footer-side">`);
document.write(`<p class = "footer-title">Contact</p>`);
document.write(`<div class = "contact">`);
document.write(`<p class = "footer-contact">1329 Oakland Street, St. Paul, Minnesota 55119<br>Email: pacifica-spa@gmail.com<br>Phone: 651-578-9699</p>`);
document.write(`</div>`);
document.write(`</div>`);
document.write(`</div>`);
document.write(`<div class = "footer-copyright"><p>Copyright 2020 &copy; All rights reserved.</p></div>`);