document.write(`<div class = "footer-container">`);
document.write(`<div class = "footer-side" >`);
document.write(`<p class = "footer-title">Hours</p>`);
document.write(`<div class  = "hours">`);
document.write(`<p class = "footer-hours"><b>Monday - Friday:</b> 10:00 a.m. - 5:00 p.m.<br><b>Saturday:</b> 9:00 a.m. - 6:00 p.m.<br><b>Sunday:</b> closed</p>`);
document.write(`</div>`);
document.write(`</div>`);
document.write(`<div class = "footer-middle">`);
document.write(`<p class = "footer-title pacifica">Pacifica</p>`);
document.write(`<p class = "footer-text">We at Pacifica are commited to giving each customer a satisfying, relaxing, and enjoyable experience.</p>`);
document.write(`<ul class="social-icons">`);
document.write(`<li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>`);
document.write(`<li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>`);
document.write(`<li><a class="linkedin" href="#"><i class="fa fa-instagram"></i></a></li>`);
document.write(`</ul>`);
document.write(`</div>`);
document.write(`<div class = "footer-side">`);
document.write(`<p class = "footer-title">Contact</p>`);
document.write(`<div class = "contact">`);
document.write(`<p class = "footer-contact">1329 Oakland Street, St. Paul, Minnesota 55119<br><b>Email:</b> pacifica-spa@gmail.com<br><b>Phone:</b> 651-578-9699</p>`);
document.write(`</div>`);
document.write(`</div>`);
document.write(`</div>`);
document.write(`<div class = "footer-copyright"><p>Copyright 2020 &copy; All rights reserved.</p></div>`);